export const SIGN_IN="SIGN_IN"
export const SIGN_UP="SIGN_UP"
export const LOAD="LOAD"
export const EDIT="EDIT"
export const GET="GET"
export const DELETE="DELETE"
export const FAIL="FAIL"
export const LOG_OUT="LOG_OUT"